### ISSUE TITLE
configparser.NoSectionError: No section: 'launchbox'

### ISSUE THREAD

**Issue by EdenEvoX** [jmriego/emulation#1]
keep on getting this when trying to run - config file is properly set:

C:\LaunchBox\emulation-master>launchbox2ael.py
Traceback (most recent call last):
  File "C:\LaunchBox\emulation-master\LaunchBox2AEL.py", line 15, in <module>
    LBDIR = config.get('launchbox', 'dir')
  File "C:\Python37\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Python37\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'launchbox'

**Comment by jmriego** [comment]
That's a strange error. It's just calling a Python library.
Can you paste here at least partly the config.ini? Maybe it's expecting some specific order

**Comment by EdenEvoX** [comment]
here is the config :)

[launchbox]
dir=C:\LaunchBox

[ael]
# dir=%LOCALAPPDATA%\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\userdata\addon_data\plugin.program.advanced.emulator.launcher
dir=%APPDATA%\kodi\userdata\addon_data\plugin.program.advanced.emulator.launcher

[dosbox]
exe=C:\DosBox\dosbox.exe
args=-conf dosbox.conf -conf "{}"

**Comment by jmriego** [comment]
I believe Python would give that error also if it just didn't find your config file. Is it exactly in **C:\LaunchBox\emulation-master\config.ini** ?

**Comment by EdenEvoX** [comment]
it wasn't for some reason and that fixed the issue - thanks for your help!!

**Comment by jmriego** [comment]
That's great. I hope it works now for you. You are probably the first user :)

**Comment by EdenEvoX** [comment]
It works great - I've been waiting for AEL to be updated for some time (and have a large launchbox database) so this is absolutely perfect, thanks for creating it.

Now time to customise my theme so the box art works!
