### ISSUE TITLE
Importing Error

### ISSUE THREAD

**Issue by tampas** [jmriego/emulation#6]
Hi,
First of all, congratulations. I've been looking for a tool to import my Launchbox Library into Kodi/AEL for ages.
thank u.

Now, i'm trying to run the script but i'm facing an error that i cannot overcome.

This is my config.ini file:
`[launchbox]
dir=C:\Games\LaunchBox

[ael]
dir=%APPDATA%\kodi\userdata\addon_data\plugin.program.advanced.emulator.launcher

[dosbox]
exe=C:\Games\DOSBox\DOSBox.exe
args=-conf dosbox.conf -conf "{}"`
I've doubled checked the folders, but when i try to import something i always gives me an error:

PS C:\emulation> python .\LaunchBox2AEL.py
Generating list of Windows games
Generating list of Nintendo Game Boy Advance games
Generating list of MS-DOS games
Generating list of Atari 2600 games
Generating list of Nintendo 64 games
Generating list of Nintendo Entertainment System games
Generating list of Arcade games
Generating list of Sega Genesis games
Traceback (most recent call last):
  File ".\LaunchBox2AEL.py", line 91, in <module>
    categories, launchers = generate_data()
  File ".\LaunchBox2AEL.py", line 33, in generate_data
    launchers = AELLaunchersCatalog(launchbox.games, DOSBOX_EXE, DOSBOX_ARGS, AELDIR)
  File "C:\emulation\launchbox\catalog.py", line 60, in games
    self._games = GamesCatalog(
  File "C:\emulation\launchbox\game.py", line 57, in __init__
    game.emulator = emulators[game.emulator]
  File "C:\emulation\launchbox\emulator.py", line 51, in __getitem__
    return self.emulators[key]
KeyError: '3e06492d-5a8f-41d5-bce5-4798abf1cb8d'

Probably it would be trivial, but i'm not getting it.
can you help?

thanks for you time..

**Comment by jmriego** [comment]
No worries! I have been using it for some time now and I'm loving this combination of LaunchBox and AEL. It's really good.

I'm not sure if there's some configuration of emulators that I'm not aware of or you have a Sega Genesis game that is not configured with any existing emulator. Whatever the case, do you mind attaching the files `C:\Games\LaunchBox\Data\Emulators.xml` and `C:\Games\LaunchBox\Data\Platforms\Sega Genesis.xml` so I can have a look?

**Comment by tampas** [comment]
Hi,
for sure, i've posted it into a paste bin tool for orgazination of this thread
[debug logs](https://paste.ee/p/iCOnz)

Thanks for your time again

**Comment by jmriego** [comment]
I'm not sure if it's just some syntax that I didn't see before but it looks to me like you have some Sega Genesis games that are not pointing to an existing emulator. If you try to open let's say "Crack Down" in LaunchBox, is it able to run the game?

**Comment by jmriego** [comment]
Hi @tampas! Did you manage to get this working? I have added some error message for the games without a valid emulator configuration if that helps
