### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by TonyBirt** [jmriego/emulation#7]
Hi Jmriego
Haven't used Kodi in a couple of years and just jumping back in now with Kodi 19.  Getting a key error and not sure what it could be?  I seem to be getting the same error with 2 different versions of Launchbox so I think it may be something I am not doing in AEL?

C:\L2K>launchbox2ael.py
Traceback (most recent call last):
  File "C:\L2K\LaunchBox2AEL.py", line 130, in <module>
    categories, launchers, collections = generate_data()
  File "C:\L2K\LaunchBox2AEL.py", line 35, in generate_data
    launchers = AELLaunchersCatalog(launchbox.games, DOSBOX_EXE, DOSBOX_ARGS, AELDIR)
  File "C:\L2K\launchbox\catalog.py", line 62, in games
    self.platforms,
  File "C:\L2K\launchbox\catalog.py", line 48, in platforms
    self._platforms = PlatformsCatalog(
  File "C:\L2K\launchbox\platform.py", line 35, in __init__
    self.platforms[platform_name].category = categories.search(category_name)
KeyError: ''

**Comment by jmriego** [comment]
hi @BirtLaden ! that looks to me like something strange in your LaunchBox catalog.

I guess `LaunchBox\Data\Parents.xml` file does not match the data in `LaunchBox\Data\Platforms.xml` for your Launchbox catalog.
Can you check in LaunchBox that `Parents.xml` file? I think you should have a Platform with no name in that file which is causing this error. Anyway, after we find out the exact issue I can transform this so it sends a warning and shows how to fix it

**Comment by jmriego** [comment]
just to be clearer. this is an example of correct data in the `Parents.xml` file. You probably have something in this file where "PlatformName" is empty or showing a platform you don't have in your catalog
![image](https://user-images.githubusercontent.com/15045950/170098957-6a0f084f-40d7-45ba-978d-9a2b97cfbaf5.png)

**Comment by TonyBirt** [comment]
Ah Legend thank you.  I created a new Launchbox install and added just 2 Platforms at this stage (Genesis, Steam), edited parents.xml to remove an empty platform, then it imported both platforms to AEL without errors.  When I open Windows platform in AEL it says default_launcher.bat not found, I remember coming across this one before but can't remember how to fix it sorry.  Sent a little something to your Paypal, this utility makes Kodi worth using.

**Comment by jmriego** [comment]
thanks a lot! that's very generous of you :)

So what I'm guessing now is that there's some issue in the emulators configuration of LaunchBox. If it cannot find which emulator it should be running this game with, it's defaulting to a file called "default_launcher.bat". I think that's a bug in this program anyway, but I also think your game emulator config is missing.

Can you try running that directly in LaunchBox by double clicking on the game? Does that work?

**Comment by TonyBirt** [comment]
Got it working by creating shortcuts for Steam games and importing those to Launchbox,  thanks.

**Comment by jmriego** [comment]
that's annoying. there should be a better way to do that. If you want, I can have a look at the .xml file. If you send me the `Launchbox/Data/Platforms/?????.xml` and maybe also `Launchbox/Data/Emulators.xml` files I'll have a look at it and let you know what I find

**Comment by TonyBirt** [comment]
Great thanks, attached emulators.xml and windows.xml
[Launchbox.zip.zip](https://github.com/jmriego/emulation/files/8795174/Launchbox.zip.zip)
l

**Comment by jmriego** [comment]
perfect, I think I found this issue and this error won't happen if you import just one game as a shortcut. I think that actually fixes all games, not just the ones where you imported the shortcuts.

Do you mind checking that? Just add any game that it's from a shortcut. If that actually solves it for you and all games start working, I know what fix I need to do in this program

**Comment by TonyBirt** [comment]
Yep that worked great.  Imported 1 game shortcut and the rest of the Steam import then opened in AEL.

**Comment by jmriego** [comment]
that's good news! In that case I have the fix ready. I just put that to the repo so if you download it now this should be fixed
